### ISSUE TITLE
マルコフ連鎖の文字化け

### ISSUE THREAD

**Issue by ryusei-koseki** [private-yusuke/botot2#12]
Windows10でマルコフ連鎖が文字化けしてしまいます
DMでも言っていますが、どちらかでご返事をお願いします。

**Comment by ryusei-koseki** [comment]
![image](https://user-images.githubusercontent.com/51506011/118394955-c27e6880-b682-11eb-94a7-673d5b5e5a24.png)

**Comment by private-yusuke** [comment]
私は主に Debian 上で動かしていて、文字化けを経験したことがなかったです。
Windows 上で botot2 を動かしたときに文字化けする問題については以前まで把握しておらず、私自身が Windows 上で動かそうと考えていなかったので、申し訳ありませんがこの問題については私が修正する予定は今のところありません。

もし今すぐこのプログラムを通常通り利用したいのであれば、WSL を利用して動作させることを推奨します。

**Comment by ryusei-koseki** [comment]
権限がなくてインストールできませんでした、親に制限されています。
動作させるにはwindowsに対応させるしかありません。
うちの親が毒親なので、前に使ってた権限アリのPCをぶっ壊されたんです
どうか対応させてください

**Comment by private-yusuke** [comment]
申し訳ありませんが、私は Windows 用に botot2 を対応させる予定はありません。
GCP（Google Cloud Platform）の無料枠にて GCE（Google Compute Engine）を利用し、Debian などの Linux ディストリビューションの仮想マシンを立てることを検討してください。この方法はブラウザとあなたの Google アカウントのみを最低限必要とし、Windows での管理者権限を持つ必要はありません。

**Comment by private-yusuke** [comment]
自己解決されたようで、MeCab の辞書の相性が悪かったみたいです。
