### ISSUE TITLE
tsconfig.json で strict を true にしたい

### ISSUE THREAD

**Issue by private-yusuke** [private-yusuke/botot2#43]
f97cf89921701952a0ff28f9675cc3c3410cd8fa 時点で `strict: true` にすると

```
Found 37 errors in 15 files.
```

と出た

**Comment by azarashi2931** [comment]
iizo

**Comment by azarashi2931** [comment]
これやってる？やってないなら自分を assign してくれればやる

**Comment by private-yusuke** [comment]
private-yusuke は取り組んでない かつ #45 が出ているので、azarashi2931 を assign しました
