### ISSUE TITLE
Renovate による `@types/node` のアップデート頻度を落としたい

### ISSUE THREAD

**Issue by private-yusuke** [private-yusuke/botot2#95]
# 概要

Renovate によって `@types/node` のパッチバージョンが上がるたびに PR が作成されているが、これは頻度が高すぎるように感じている。

`@types/node` は型定義ファイルのみを持つパッケージであり、botot2 自体の動作には直接の影響を及ぼさない `devDependencies` のうちの 1 つであることから、頻度を落とすことによって生じる問題はほとんど無い・無視してよいものであると考えている。

そこで、暫定処置として Renovate には `@types/node` に限り隔週で PR を出してもらうようにしたい。

## 実現方法

ref: https://docs.renovatebot.com/key-concepts/scheduling/#schedule-when-to-update-specific-dependencies

以下のような項目を `renovate.json` に追加すればよいのではないかと考えている。

```json
{
  "packageRules": [
    {
      "matchPackageNames": ["@types/node"],
      "schedule": ["every 2 weeks on monday"]
    }
  ]
}

```

**Comment by azarashi2931** [comment]
そもそも重要でないパッケージの patch リリースを auto merge にすることも検討してよいと思う。
あとは全ての更新について weekly で PR ができるようにするとかもありうる。

**Comment by private-yusuke** [comment]
そしたら `devDependencies` の patch リリースの更新 PR は auto merge するような設定にしようかな。

**Comment by azarashi2931** [comment]
いいね
